Create readme and linters
udeaghad/hello-microverse-project pull request #1
Opened 2022-04-20 19:25 UTC by udeaghad

create linters, html and css file for review

2022-04-20 22:02 UTC, mahbubul14 requested changes
Hi @udeaghad ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Check the comments under the review for more suggestions. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.

### Optional suggestions

- [ ] The commit message should be written in the imperative tense and the first letter should be capitalized. `Ex: "Fix bug" instead of "fix bug or fixed bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-20 22:02 UTC, mahbubul14 commented on .gitignore
> +test.md
- [ ] Kindly add `node_modules` in the `.gitignore` file.

2022-04-20 22:02 UTC, mahbubul14 commented on README.md
> +- LinkedIn: [LinkedIn]
- [ ] Kindly add your social links for this part. Here is an example of how to do it linkable:

`- GitHub: [@githubhandle](https://github.com/githubhandle)`

2022-04-20 23:09 UTC, udeaghad commented on README.md
> +- LinkedIn: [LinkedIn]
link address updated appropriately

2022-04-21 05:24 UTC, udeaghad commented on .gitignore
> +test.md
node_modules ad.ded in the .gitignore file.

2022-04-21 09:47 UTC, codepantha approved these changes
Hi @udeaghad 👋,

## STATUS: APPROVED ✔️  

Good job making the requested changes 👏 👏 
Your project is now complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 10:02 UTC, merged